name: New Issue Message
on:
  issues:
    types: [closed]
jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Automatic Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}        
          issue-number: ${{ github.event.issue.number }}
          body: |
            Attention: ${{ github.event.issue.number }} has been closed. Thank you for your assistance!
